name: devinci
description: devinci portail app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.0+50

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.0
  flutter_secure_storage: ^3.3.5 # permet l'accès au secure storage de l'appareil pour stocker les identifiants de l'utilisateur et les tokens de connection
  cupertino_icons: ^1.0.0
  html: ^0.14.0+4
  characters: ^1.0.0
  syncfusion_flutter_core: ^18.4.42
  syncfusion_flutter_calendar: ^18.4.42
  syncfusion_localizations: ^18.4.42
  syncfusion_flutter_datagrid: ^18.4.42-beta
  syncfusion_flutter_pdfviewer: ^18.4.42-beta
  pull_to_refresh: 1.6.3
  flutter_statusbarcolor: ^0.2.3 # permet de changer la couleur de la barre d'état et de navigation sur android et ios
  package_info: ^0.4.3+4
  flutter_email_sender: ^4.0.0 # permet d'appeler les fonctions d'envoi de mail natives
  path_provider: ^1.6.27 # permet de sauvegarder des fichiers dans des dossiers approprié au sein des appareils
  shared_preferences: ^0.5.12+4 # permet de modifier les shared_preferences
  flutter_markdown: ^0.5.2 # permet de convertir du Markdown en RichText, utilisé pour l'affichage du changelog des mise à jour
  modal_bottom_sheet: ^1.0.0 # permet d'afficher un modal bottom sheet, utilisé pour afficher la page de paramètres
  flutter_phoenix: ^0.1.0 # permet de relancer l'application sans véritablement la quitter, une sorte de refresh, utile lorsque l'utilisateur se déconnecte
  share_extend: ^1.1.9 # permet d'appeler le volet de partage natif des différents os et de partager des fichiers.
  flutter_svg: ^0.19.1 # permet l'affichage d'image svg
  recase: ^3.0.1 # permet de transformer n'importe quelle phrase en flutter_svg
  diacritic: ^0.1.1 # permet de supprimer les accents et autres caractères ambigu dans les nom de fichier pour l'enregistrement dans les fichiers de l'appareil
  sembast: ^2.4.8+1 # sembast db stands for Simple Embedded Application Store database | système de base de donnée NoSQL pour sauvegarder les notes et determiner quelles notes sont nouvelles.
  about: ^1.4.0 # Affiche une page A propos, qui décrit l'application et les différentes licenses.
  connectivity: ^2.0.2 # permet de connaître l'état de la connection internet de l'appareil
  cupertino_rounded_corners: ^1.1.3
  confetti: ^0.5.4+1
  sentry_flutter: ^4.0.4
  onesignal_flutter: ^2.6.2
  url_launcher: ^5.7.10
  smooth_page_indicator: ^0.2.0
  easy_localization: ^2.3.3
  wiredash: ^0.4.2
  flutter_whatsnew:
    git:
      url: https://github.com/antoineraulin/flutter_whatsnew
  showcaseview: ^0.1.6
  one_context: ^0.5.0
  purchases_flutter: ^2.0.3
  matomo: ^0.0.6
  f_logs:
    git:
      url: https://github.com/antoineraulin/Flogs
  crypto: ^2.1.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

  fonts:
    - family: DevinciIcons
      fonts:
        - asset: fonts/DevinciIcons.ttf
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans/ProductSans-Black.ttf
          weight: 900
        - asset: fonts/ProductSans/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/ProductSans/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/ProductSans/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ProductSans/ProductSans-Italic.ttf
          style: italic
        - asset: fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: fonts/ProductSans/ProductSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: fonts/ProductSans/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ProductSans/ProductSans-Regular.ttf
        - asset: fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: fonts/ProductSans/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic
